### ISSUE TITLE
.map files

### ISSUE THREAD

**Issue by dennmtr** [alexandre-abrioux/gulp-rev-dist-clean#13]
.map files are not included in the rev-manifest.json so if for example app-HASH.js exists in the manifest file and app-HASH.js.map exists in the folder too, app-HASH.js.map file be deleted.

if i exclude .map files from src glob, old map files will never be deleted

**Comment by alexandre-abrioux** [comment]
@dennmtr Thanks for the feedback! I introduced a new option `keepSourceMapFiles`, you can use it right now in [v3.2.0](https://github.com/alexandre-abrioux/gulp-rev-dist-clean/releases/tag/v3.2.0).
