### ISSUE TITLE
Add del force option

### ISSUE THREAD

**Issue by omarabid** [alexandre-abrioux/gulp-rev-dist-clean#3]
If your files are outside the current directory where Gulp is running, this script will fail with the following error

```
	throw new Error('Cannot delete files/folders outside the current working directory. Can be overriden with the `force` option.');
```

I think it is possible to fix this by implementing the following option: https://stackoverflow.com/questions/44106774/cannot-force-deleting-files-outside-of-current-folder-typeerror-glob-pattern-s

I can push a pull request if you are okay with merging it.

**Comment by alexandre-abrioux** [comment]
Sure, PRs are welcome! You can add a `force` option, I'll gladly merge it. The only requirements are to add a test case and to update the `README.md` (just add the new option in the [Options](https://github.com/alexandre-abrioux/gulp-rev-dist-clean#options) category).

**Comment by alexandre-abrioux** [comment]
You can now use the new `delOptions` to pass down the `force` option to the `del` module. See https://github.com/alexandre-abrioux/gulp-rev-dist-clean/pull/12
